name: Build and deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install --from-lockfile
      - name: Build project
        run: yarn build:prod
        env:
          DEATHNOTE_DATA_API_HOSTNAME: ${{ secrets.DEATHNOTE_DATA_API_HOSTNAME }}
          DEATHNOTE_SIGNUP_API_HOSTNAME: ${{ secrets.DEATHNOTE_SIGNUP_API_HOSTNAME }}
          DEATHNOTE_GITHUB_CLIENT_ID: ${{ secrets.DEATHNOTE_GITHUB_CLIENT_ID }}
          DEATHNOTE_GITHUB_REDIRECT_URI: ${{ secrets.DEATHNOTE_GITHUB_REDIRECT_URI }}
          DEATHNOTE_PROVIDER_NETWORK: ${{ secrets.DEATHNOTE_PROVIDER_NETWORK }}
          DEATHNOTE_REGISTRY_CONTRACT_ADDRESS: ${{ secrets.DEATHNOTE_REGISTRY_CONTRACT_ADDRESS }}
          DEATHNOTE_TYPEFORM_APPLY_URL: ${{ secrets.DEATHNOTE_TYPEFORM_APPLY_URL }}
          DEATHNOTE_TYPEFORM_SUBMIT_URL: ${{ secrets.DEATHNOTE_TYPEFORM_SUBMIT_URL }}
          DEATHNOTE_SENTRY_DSN: ${{ secrets.DEATHNOTE_SENTRY_DSN }}
          DEATHNOTE_SENTRY_ENVIRONMENT: ${{ secrets.DEATHNOTE_SENTRY_ENVIRONMENT }}
          DEATHNOTE_SENTRY_RELEASE: ${{ secrets.GITHUB_SHA }}
          DEATHNOTE_SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.DEATHNOTE_SENTRY_TRACES_SAMPLE_RATE }}
          DEATHNOTE_SENTRY_AUTH_TOKEN: ${{ secrets.DEATHNOTE_SENTRY_AUTH_TOKEN }}
          DEATHNOTE_SENTRY_ORG: ${{ secrets.DEATHNOTE_SENTRY_ORG }}
          DEATHNOTE_SENTRY_PROJECT: ${{ secrets.DEATHNOTE_SENTRY_PROJECT }}
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync dist s3://onlydust-deathnote-frontend
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E26UTVUNWI160B --paths "/*"
      - name: Uninstall yarn
        run: npm uninstall -g yarn
